export interface Game {
  id: string
  title: string
  slug: string
  description?: string
}

export const games: Game[] = [
  { id: '1', title: 'Fruit Ninja', slug: 'fruitninja' },
  { id: '2', title: '1v1.lol', slug: '1v1lol' },
  { id: '3', title: 'Taisei Project', slug: 'taiseiproject' },
  { id: '4', title: 'Metroid Fusion', slug: 'metroidfusion' },
  { id: '5', title: 'Celeste (PICO-8 ORIGINAL VERSION)', slug: 'celeste' },
  { id: '6', title: 'Slope', slug: 'slope' },
  { id: '7', title: 'Slope Plus', slug: 'slopeplus' },
  { id: '8', title: 'Slope 2 Player', slug: 'slope2player' },
  { id: '9', title: 'Eaglercraft 1.5.2', slug: 'eaglercraft152' },
  { id: '10', title: 'Eaglercraft 1.12.2', slug: 'eaglercraft122' },
  { id: '11', title: 'Mario Combat', slug: 'mariocombat' },
  { id: '12', title: 'Super Mario Bros', slug: 'supermariobros' },
  { id: '13', title: 'Mario Kart 64', slug: 'mariokart64' },
  { id: '14', title: "Baldi's Basics", slug: 'baldibasics' },
  { id: '15', title: 'Vex', slug: 'vex' },
  { id: '16', title: 'Vex 2', slug: 'vex2' },
  { id: '17', title: 'Vex 3', slug: 'vex3' },
  { id: '18', title: 'Volley Random', slug: 'volleyrandom' },
  { id: '19', title: 'Soccer Random', slug: 'soccerrandom' },
  { id: '20', title: 'Basket Random', slug: 'basketrandom' },
  { id: '21', title: 'Boxing Random', slug: 'boxingrandom' },
  { id: '22', title: 'Nuts and Bolts Screwing Puzzle', slug: 'nutsnbolts' },
  { id: '23', title: 'Cookie Clicker', slug: 'cookieclicker' },
  { id: '24', title: 'Super Smash Bros', slug: 'supersmashbros' },
  { id: '25', title: 'Soccer Skills World Cup', slug: 'soccerskills' },
  { id: '26', title: 'N-Gon', slug: 'ngon' },
  { id: '27', title: 'Drift Hunters', slug: 'drifthunters' },
  { id: '28', title: 'Subway Surfers: Winter Holiday', slug: 'subwaysurferswinterholiday' },
  { id: '29', title: 'Subway Surfers: Miami', slug: 'subwaysurfersmiami' },
  { id: '30', title: 'Rooftop Snipers', slug: 'rooftopsnipers' },
  { id: '31', title: 'Rooftop Snipers 2', slug: 'rooftopsnipers2' },
  { id: '32', title: 'Bitlife', slug: 'bitlife' },
  { id: '33', title: 'Fancy Pants Adventure', slug: 'fancypantsadventure' },
  { id: '34', title: 'Line Rider', slug: 'linerider' },
  { id: '35', title: 'Deltarune', slug: 'deltarune' },
  { id: '36', title: 'Unfair Undyne', slug: 'unfairundyne' },
  { id: '37', title: 'Ultrakill', slug: 'ultrakill' },
  { id: '38', title: 'Pokemon Fire Red', slug: 'pokemonfirered' },
  { id: '39', title: 'Pokemon Leaf Green', slug: 'pokemonleafgreen' },
  { id: '40', title: 'Pokemon Unbound', slug: 'pokemonunbound' },
  { id: '41', title: 'Pokemon Stadium', slug: 'pokemonstadium' },
  { id: '42', title: 'Pokemon Emerald', slug: 'pokemonemerald' },
  { id: '43', title: 'Pokemon Emerald: Rouge', slug: 'pokemonemeraldrg' },
  { id: '44', title: 'Pokemon Ruby', slug: 'pokemonruby' },
  { id: '45', title: 'Sonic the Hedgehog', slug: 'sonicthehedgehog' },
  { id: '46', title: 'Riddle School', slug: 'riddleschool' },
  { id: '47', title: 'Red Ball 4', slug: 'redball' },
  { id: '48', title: 'OvO', slug: 'ovo' },
  { id: '49', title: 'OvO 2', slug: 'ovo2' },
  { id: '50', title: 'FIFA 11', slug: 'fifa11' },
  { id: '51', title: 'Funny Shooter 2', slug: 'funnyshooter2' },
  { id: '52', title: 'Retro Bowl', slug: 'retrobowl' },
  { id: '53', title: 'Retro Bowl College', slug: 'retrobowlcollege' },
  { id: '54', title: 'Tiny Fishing', slug: 'tinyfishing' },
  { id: '55', title: 'Doom', slug: 'doom' },
  { id: '56', title: 'Among Us', slug: 'amongus' },
  { id: '57', title: 'Geometry Dash', slug: 'geometrydash' },
  { id: '58', title: 'Geometry Dash DEMAKE', slug: 'geometrydashdemake' },
  { id: '59', title: 'Crossy Roads', slug: 'crossyroads' },
  { id: '60', title: 'MotoX3M', slug: 'motox3m' },
  { id: '61', title: 'Omori', slug: 'omori' },
  { id: '62', title: 'Bad Time Simulator', slug: 'badtimesimulator' },
  { id: '63', title: 'CSGO Clicker', slug: 'csgoclicker' },
  { id: '64', title: 'Yume Nikki', slug: 'yumenikki' },
  { id: '65', title: 'Friday Night Funkin', slug: 'fnf' },
  { id: '66', title: 'Snow Battle IO', slug: 'snowbattle' },
  { id: '67', title: 'The Legend of Zelda: Ocarina of Time', slug: 'ocarina' },
  { id: '68', title: 'Karlson', slug: 'karl' },
  { id: '69', title: 'Metal Gear Solid', slug: 'metal' },
  { id: '70', title: 'Jetpack Joyride', slug: 'jet' },
  { id: '71', title: "Five Nights at Freddy's", slug: 'fnaf' },
  { id: '72', title: "Five Nights at Freddy's 2", slug: 'fnaf2' },
  { id: '73', title: "Five Nights at Freddy's 3", slug: 'fnaf3' },
  { id: '74', title: "Five Nights at Freddy's 4", slug: 'fnaf4' },
  { id: '75', title: 'Hollow Knight', slug: 'hollow' },
  { id: '76', title: 'Granny', slug: 'granny' },
  { id: '77', title: 'Granny 2', slug: 'granny2' },
  { id: '78', title: 'Ice Dodo', slug: 'icedodo' },
  { id: '79', title: 'Clash of Vikings', slug: 'clash' },
  { id: '80', title: 'Agar IO', slug: 'agario' },
  { id: '81', title: 'Awesome Tanks', slug: 'awesome' },
  { id: '82', title: 'Binding Of Issac: Wrath of the Lamb', slug: 'binding' },
  { id: '83', title: 'Hollow Knight: Silksong (PICO-8 REMAKE)', slug: 'silksong' },
  { id: '84', title: 'Basketball Stars', slug: 'basketstars' },
  { id: '85', title: 'R.E.P.O', slug: 'repo' },
  { id: '86', title: 'Football Bros', slug: 'footbros' },
  { id: '87', title: 'Baseball Bros', slug: 'basebros' },
  { id: '88', title: 'Basket Bros', slug: 'basketbros' },
  { id: '89', title: 'Snow Rider 3D', slug: 'snowrider' },
  { id: '90', title: 'Stick Slasher', slug: 'stickslasher' },
  { id: '91', title: 'Block Blast', slug: 'blockblast' },
  { id: '92', title: 'Super Mario 64', slug: 'supermario64' },
  { id: '93', title: 'They Are Coming', slug: 'theycomin' },
  { id: '94', title: 'Paper IO', slug: 'paperio' },
  { id: '95', title: 'Gladdihoppers', slug: 'gladdihoppers' },
  { id: '96', title: 'Kindergarten', slug: 'kinder' },
  { id: '97', title: 'Kindergarten 2', slug: 'kinder2' },
  { id: '98', title: 'Kindergarten 3', slug: 'kinder3' },
  { id: '99', title: 'Silent Hill PS1', slug: 'silentps1' },
  { id: '100', title: 'Call of Duty 4 - Modern Warfare', slug: 'codmw4' },
  { id: '101', title: 'House of Hazards', slug: 'hazard' },
]

export function getGameBySlug(slug: string): Game | undefined {
  return games.find(game => game.slug === slug)
}
